version: "3.8"
services: 
    rancher:
        container_name: rancher-server
        image: rancher/rancher
        ports:
        - 80:80
        - 443:443
        networks:
        - rancher_network
        command:
            --acme-domain localhost
        restart: always
networks:
    rancher_network:
      name: rancher_network
